### ISSUE TITLE
Purpose of the website

### ISSUE THREAD

**Issue by arthurvguide** [arthurvguide/ask-japanese-restaurant#3]
As a **user* I can **understand the purpose of the website** so that **I use its features**

### Acceptance Criteria
* Acceptance Criteria 1: User can navigate to a book page
* Acceptance Criteria 2: User can navigate to a contact page
* Acceptance Criteria 3: User can find out the restaurant opening time
* Acceptance Criteria 4: User can find out where the restaurant is based
* Acceptance Criteria 5: User can navigate to the restaurant's social media 

### Tasks
- [ ] Install necessary Django modules and packages
- [ ] Configure settings
- [ ] Perform initial deployment
- [ ] Create templates for base, home, contact, and book pages and its styles
- [ ] Create views for home, contact, and book pages
